version: '3.8'

services:
  mysql_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Wce@2022
      MYSQL_DATABASE: todoapp
    ports:
      - "3308:3306"
    networks:
      - my-network
  redis_db:
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=Redsecret
    ports:
      - "6379:6379"
    networks:
      - my-network
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
      - redis_db
    networks:
      - my-network
networks:
  my-network:
    external: true
