server:
  host: "localhost"
  port: 8080

database:
  host: "localhost"
  port: 3306
  name: "mysql"
  user: "root"
  password: "Wce@2022"
  database: "todoapp"

redis:
  host: "localhost"
  port: 6379
  password: "Redsecret"
  db: 0

email:
  host: "smtp.gmail.com"
  port: "587"
  from: "test2022pratibha@gmail.com"
  password: "tpqd dacb wtkd mjpx"